import './style.css';
import './enhancements.css';
import './spin-animation.css';
import './audio-controls.css';
import './console-layout.css';
import './compact-game.css';
import './free-game-win.css';
import './compact-audio.css';
import './win-details.css';
import './bonus-symbols.css';
import './recharge-wallet.css';
import { GAME_CONFIG, REEL_STRIP, reelStripForDragon, DRAGONS, type SymbolId } from './config';
import { scatterPityChance, spin, type Grid, type SpinResult } from './game';
import { getVolume, isMuted, isMusicEnabled, playScatterSound, playSpinSound, playWinSound, setVolume, startMusic, toggleMusic, toggleMute } from './audio';

type Ledger = { deposits: number; wagered: number; won: number; spins: number };
type HistoryItem = { time: string; bet: number; win: number; label: string };
type WalletState = { balance: number; ledger: Ledger; history: HistoryItem[]; freeSpins: number; dragonId: string | null; lastCheckIn: string; rescueUsed: boolean; scatterMisses: number; freeGameWin: number; pendingFreeGameSelection: boolean; currencyReset: boolean };
const app = document.querySelector<HTMLDivElement>('#app')!;
const saved = JSON.parse(localStorage.getItem('dragons-state') ?? 'null') as WalletState | null;
let state: WalletState = saved ?? { balance: GAME_CONFIG.initialBalance, ledger: { deposits: 0, wagered: 0, won: 0, spins: 0 }, history: [], freeSpins: 0, dragonId: null, lastCheckIn: '', rescueUsed: false, scatterMisses: 0, freeGameWin: 0, pendingFreeGameSelection: false, currencyReset: true };
state.scatterMisses ??= 0;
state.freeGameWin ??= 0;
state.pendingFreeGameSelection ??= false;
if (!state.currencyReset) {
  state.balance = 0;
  state.ledger = { deposits: 0, wagered: 0, won: 0, spins: 0 };
  state.history = [];
  state.freeSpins = 0;
  state.dragonId = null;
  state.scatterMisses = 0;
  state.freeGameWin = 0;
  state.pendingFreeGameSelection = false;
  state.currencyReset = true;
  localStorage.setItem('dragons-state', JSON.stringify(state));
}
let betIndex = 2;
let isSpinning = false;
let autoSpins = 0;
let lastResult: SpinResult | null = null;
let pendingResult: SpinResult | null = null;
let spinTimer: number | null = null;
let stopTimers: number[] = [];
let scatterSoundedColumns = new Set<number>();
let dragonSelection = state.pendingFreeGameSelection && state.freeSpins === 0;
let freeGameReady = false;
let pendingFreeGameSelection = state.pendingFreeGameSelection;
let freeSessionWin = state.freeGameWin;
let freeSummary: number | null = null;
let winDisplayIndex = 0;
let winDisplayTimer: number | null = null;
let grid: Grid = spin(50).grid;
const money = (value: number) => `R${value.toLocaleString('zh-CN', { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
const RECHARGE_AMOUNTS = [10, 20, 50, 100, 200];
const bet = () => GAME_CONFIG.betSteps[betIndex];
const symbolMeta = (id: SymbolId) => GAME_CONFIG.symbols.find((symbol) => symbol.id === id)!;
const persist = () => localStorage.setItem('dragons-state', JSON.stringify(state));
const today = () => new Date().toISOString().slice(0, 10);
const dragon = () => DRAGONS.find((item) => item.id === state.dragonId);
const rtp = () => state.ledger.wagered ? ((state.ledger.won / state.ledger.wagered) * 100).toFixed(1) : '0.0';
const scatterProbability = () => { const positions = GAME_CONFIG.rows * GAME_CONFIG.columns; const scatterChance = REEL_STRIP.filter((symbol) => symbol === 'scatter').length / REEL_STRIP.length; const combinations = (n: number, k: number) => { let result = 1; for (let index = 1; index <= k; index += 1) result *= (n - index + 1) / index; return result; }; const noTrigger = Array.from({ length: 3 }, (_, count) => combinations(positions, count) * scatterChance ** count * (1 - scatterChance) ** (positions - count)).reduce((sum, value) => sum + value, 0); return ((1 - noTrigger) * 100).toFixed(2); };

function render() {
  const rescueReady = state.balance < bet() && !state.rescueUsed;
  app.innerHTML = `<main class="shell dragons-shell"><header class="topbar"><div class="brand"><span class="brand-mark dragon-mark">◈</span><div><strong>五龙秘宝</strong><small>5 DRAGONS · SOLO SIM</small></div></div><div class="top-actions"><button class="wallet-chip" data-action="shop" title="打开虚拟商城">＋ <strong>${money(state.balance)}</strong><em>R</em></button><button class="icon-button ${isMusicEnabled() ? 'is-on' : ''}" data-action="sound" aria-label="切换音乐">${isMusicEnabled() ? '♫' : '♪'}</button><button class="icon-button ${isMuted() ? '' : 'is-on'}" data-action="volume" aria-label="控制音量">${isMuted() ? '🔇' : '🔊'}</button><button class="icon-button" data-action="ledger" aria-label="查看账本">▤</button></div></header>
<section class="machine dragon-machine"><div class="machine-head"><div><span class="eyebrow">5 × 3 REELS · CONNECTING LINES</span><h2>${dragonSelection ? 'FREE GAME' : `${dragon()?.glyph ?? '🐉'} ${dragon()?.label ?? '五龙秘宝'}`}</h2></div><div class="feature-status ${state.freeSpins ? 'active' : ''}">${dragonSelection ? '选择守护神龙' : state.freeSpins ? `免费游戏 ${state.freeSpins} 局` : '准备旋转'}</div></div><div class="reels-wrap ${dragonSelection ? 'dragon-selection-stage' : ''}">${dragonSelection ? renderDragonSelection() : `<div class="reels ${isSpinning ? 'spinning' : ''}" data-reels>${renderGrid()}</div><div class="reel-glow"></div><div class="scanline"></div>${freeSummary !== null ? renderFreeSummary() : ''}`}</div><div class="result-bar ${freeSessionWin > 0 ? 'free-win-bar' : ''}"><span>${dragonSelection ? '选择一条龙，随后自动开始免费游戏' : state.dragonId && (state.freeSpins > 0 || freeSessionWin > 0) ? `本轮 +${money(lastResult?.totalWin ?? 0)} · 免费累计 +${money(freeSessionWin)}` : isSpinning ? '卷轴依次停止中 · 可快速结算' : lastResult?.scatterCount && lastResult.scatterCount >= 3 ? `龙珠出现 ${lastResult.scatterCount} 个` : lastResult?.wins.length ? `命中 ${lastResult.wins.length} 组连线` : '龙珠会在任意位置出现'}</span><strong>${lastResult?.totalWin ? `+${money(lastResult.totalWin)}` : '—'}</strong></div>${!dragonSelection ? renderWinDetails() : ''}</section>
<section class="controls machine-console"><div class="console-stat"><span class="control-label">总金额</span><strong>${money(state.balance)}</strong><small>R</small></div><div class="bet-control"><span class="control-label">倍率 / 每局</span><div class="bet-stepper"><button data-action="bet-down" ${isSpinning ? 'disabled' : ''}>−</button><strong>${money(bet())}</strong><button data-action="bet-up" ${isSpinning ? 'disabled' : ''}>＋</button></div><small>横斜连线</small></div><button class="spin-button dragon-spin" data-action="spin" ${!isSpinning && !state.freeSpins && state.balance < bet() ? 'disabled' : ''}><span class="spin-icon">${isSpinning ? '»' : '✦'}</span><span>${isSpinning ? '快速结算' : state.freeSpins ? '免费旋转' : '旋转'}</span></button><div class="auto-control"><span class="control-label">自动</span><select data-action="auto" ${isSpinning ? 'disabled' : ''}><option value="0">关闭</option><option value="10">10 局</option><option value="25">25 局</option></select><small>${rescueReady ? '可领取救济' : '自动停止'}</small></div></section>
<div class="audio-console"><button class="console-icon" data-action="sound" aria-label="背景音乐">${isMusicEnabled() ? '♫' : '♪'}</button><button class="console-icon" data-action="volume" aria-label="音量">${isMuted() ? '🔇' : '🔊'}</button></div><div class="volume-popover hidden" data-volume-popover><label>音量 <input data-volume type="range" min="0" max="1" step="0.01" value="${getVolume()}"></label><button data-action="mute">${isMuted() ? '取消静音' : '静音'}</button></div></main>`;
  app.querySelector('.dragons-shell')?.insertAdjacentHTML('afterbegin', renderRechargeRail());
  bindEvents();
}
function renderRechargeRail() { return `<aside class="recharge-rail"><div class="recharge-balance"><span>可用余额</span><strong data-balance-target>${money(state.balance)}</strong></div><span class="recharge-label">充值金额</span><div class="recharge-options">${RECHARGE_AMOUNTS.map((amount) => `<button class="recharge-button" data-deposit="${amount}" aria-label="充值 R${amount}"><span>＋</span><strong>R${amount}</strong></button>`).join('')}</div><small class="recharge-note">本地虚拟钱包</small></aside>`; }
function winningCells() { const cells = new Set<string>(); lastResult?.wins.forEach((win) => win.cells.forEach((cell) => cells.add(cell))); return cells; }
function renderDragonSelection() { if (freeGameReady) return `<div class="dragon-selection free-game-ready"><span class="eyebrow">BONUS TRIGGERED</span><strong class="ready-dragon">◈</strong><h3>免费游戏已触发</h3><p>龙珠已经集齐，准备选择你的守护神龙。</p><button class="enter-free-button" data-action="enter-free-game">进入免费游戏</button></div>`; return `<div class="dragon-selection"><span class="eyebrow">FREE GAME BONUS</span><h3>选择你的守护神龙</h3><div class="dragon-choice">${DRAGONS.map((item) => `<button data-dragon-choice="${item.id}"><span class="choice-dragon ${item.tone}">${item.glyph}</span><b>${item.label}</b><small>${item.spins} 局 · ${item.multipliers.join('/')}×</small></button>`).join('')}</div></div>`; }
function renderFreeSummary() { return `<div class="free-summary"><div class="coin-rain">${Array.from({ length: 16 }, (_, index) => `<i style="--i:${index}">✦</i>`).join('')}</div><span class="eyebrow">FREE GAME COMPLETE</span><strong class="summary-amount">+${money(freeSummary ?? 0)}</strong><h3>免费游戏总盈利</h3><p>${dragon()?.glyph ?? '🐉'} ${dragon()?.label ?? '守护神龙'} · ${money(freeSummary ?? 0)}</p><button class="summary-button" data-action="close-free-summary">继续游戏</button></div>`; }
function renderWinDetails() { if (!lastResult?.wins.length) return '<div class="win-detail win-detail-empty" aria-hidden="true"></div>'; const win = lastResult.wins[winDisplayIndex % lastResult.wins.length]; const total = lastResult.totalWin; return `<div class="win-detail"><span class="win-detail-line">中奖线 ${winDisplayIndex % lastResult.wins.length + 1} / ${lastResult.wins.length}</span><strong>${win.symbol.glyph} ${win.symbol.label} · ${win.count} 连</strong><b>本线奖励 +${money(win.amount)}</b><small>本局中奖合计 ${money(total)}${lastResult.wins.length > 1 ? ' · 自动展示下一条' : ''}</small></div>`; }
function startWinDetails() { if (!lastResult || lastResult.wins.length < 2) return; if (winDisplayTimer !== null) window.clearInterval(winDisplayTimer); winDisplayTimer = window.setInterval(() => { winDisplayIndex = (winDisplayIndex + 1) % lastResult!.wins.length; const detail = app.querySelector<HTMLElement>('.win-detail'); if (detail) { detail.classList.remove('win-detail-enter'); void detail.offsetWidth; detail.classList.add('win-detail-enter'); detail.outerHTML = renderWinDetails(); } }, 1200); }
function renderGrid() { const winners = winningCells(); const displayGrid = isSpinning && pendingResult ? pendingResult.grid : grid; const reelStrip = reelStripForDragon(dragon()?.id ?? null); return Array.from({ length: GAME_CONFIG.columns }, (_, columnIndex) => { const rollingIds = Array.from({ length: 8 }, () => reelStrip[Math.floor(Math.random() * reelStrip.length)]); const ids = [...rollingIds, ...displayGrid.map((row) => row[columnIndex])]; return `<div class="reel-column reel-${columnIndex}"><div class="reel-strip">${ids.map((id, index) => { const rowIndex = index - 8; const symbol = symbolMeta(id); return `<div class="symbol dragon-symbol ${symbol.tone} ${rowIndex >= 0 && winners.has(`${rowIndex}-${columnIndex}`) ? 'winner' : ''}"><span>${symbol.glyph}</span><small>${symbol.label}</small></div>`; }).join('')}</div></div>`; }).join(''); }
function renderPaytable() { return GAME_CONFIG.symbols.filter((symbol) => ['yellow', 'blue', 'black', 'red', 'white'].includes(symbol.id)).map((symbol) => `<div class="pay-row"><span class="pay-symbol ${symbol.tone}">${symbol.glyph}</span><span>${symbol.label}</span><strong>${symbol.payouts[3] ?? '—'}×</strong><strong>${symbol.payouts[4] ?? '—'}×</strong><strong>${symbol.payouts[5] ?? '—'}×</strong></div>`).join(''); }
function renderHistory() { return state.history.length ? state.history.slice(0, 5).map((item) => `<div class="history-row"><span>${item.time}<small>${item.label}</small></span><strong class="${item.win ? 'positive' : ''}">${item.win ? `+${money(item.win)}` : '—'}</strong></div>`).join('') : '<div class="empty">旋转后，战果会显示在这里</div>'; }
function renderModals(rescueReady: boolean) { return `<div class="modal hidden" data-modal="shop"><div class="modal-card shop-card"><button class="modal-close" data-action="close">×</button><span class="eyebrow">LOCAL WALLET</span><h2>虚拟商城</h2><p>点击档位立即入账，仅用于本地娱乐仿真。</p><div class="deposit-grid">${[['10', '10', '充值'], ['20', '20', '充值'], ['50', '50', '充值'], ['100', '100', '充值'], ['200', '200', '充值']].map(([cash, coins, note]) => `<button data-deposit="${coins}"><b>R${cash}</b><strong>${coins}</strong><small>${note}</small></button>`).join('')}</div><div class="gm-row"><span>GM 快捷充值</span><button data-action="gm">F2 / 自定义</button></div></div></div><div class="modal hidden" data-modal="ledger"><div class="modal-card"><button class="modal-close" data-action="close">×</button><span class="eyebrow">ACCOUNT LEDGER</span><h2>本地账本</h2><div class="ledger-big"><b>${money(state.balance)}</b><span>当前余额</span></div><div class="ledger-list"><span>初始资金 <b>${money(GAME_CONFIG.initialBalance)}</b></span><span>累计充值 <b>${money(state.ledger.deposits)}</b></span><span>累计下注 <b>${money(state.ledger.wagered)}</b></span><span>累计赢分 <b>${money(state.ledger.won)}</b></span><span>实际 RTP <b>${rtp()}%</b></span></div></div></div><div class="modal hidden" data-modal="rules"><div class="modal-card"><button class="modal-close" data-action="close">×</button><span class="eyebrow">HOW TO PLAY</span><h2>五龙玩法</h2><div class="rule-list"><div><b>01</b><span>5×3 卷轴，横斜连线：同一符号从左至右连续出现 3 列即可获奖。</span></div><div><b>02</b><span>五色神龙可替代普通可赔付符号。3 个以上龙珠 Scatter 触发免费游戏。</span></div><div><b>03</b><span>免费游戏开始时选择一条神龙，不同神龙拥有不同局数和倍数；之后牌面只出现这条龙。</span></div><div><b>04</b><span>F2 或钱包按钮可打开本地虚拟充值，不连接真实支付。</span></div></div></div></div><div class="modal ${rescueReady ? '' : 'hidden'}" data-modal="rescue"><div class="modal-card rescue-card"><span class="eyebrow">BANKRUPT RESCUE</span><h2>龙神救济</h2><p>余额不足以继续旋转，领取 R10 虚拟救济重新出发。</p><button class="spin-button" data-action="rescue">领取救济</button></div></div><div class="modal hidden" data-modal="dragon"><div class="modal-card"><span class="eyebrow">FREE GAME</span><h2>选择你的守护神龙</h2><div class="dragon-choice">${DRAGONS.map((item) => `<button data-dragon-choice="${item.id}"><span>${item.glyph}</span><b>${item.label}</b><small>${item.spins} 局 · ${item.multipliers.join('/')}×</small></button>`).join('')}</div></div></div>`; }
function openModal(name: string) { app.querySelector(`[data-modal="${name}"]`)?.classList.remove('hidden'); }
function closeModals() { app.querySelectorAll<HTMLElement>('[data-modal]').forEach((modal) => modal.classList.add('hidden')); }
function bindEvents() { app.querySelectorAll<HTMLElement>('[data-action]').forEach((element) => element.addEventListener('click', () => handleAction(element.dataset.action!))); app.querySelectorAll<HTMLElement>('[data-deposit]').forEach((element) => element.addEventListener('click', () => deposit(Number(element.dataset.deposit), element))); app.querySelectorAll<HTMLElement>('[data-dragon-choice], [data-dragon]').forEach((element) => element.addEventListener('click', () => chooseDragon(element.dataset.dragonChoice ?? element.dataset.dragon!))); app.querySelector<HTMLSelectElement>('[data-action="auto"]')?.addEventListener('change', (event) => { autoSpins = Number((event.target as HTMLSelectElement).value); if (autoSpins) runSpin(); }); app.querySelector<HTMLInputElement>('[data-volume]')?.addEventListener('input', (event) => setVolume(Number((event.target as HTMLInputElement).value))); }
function deposit(amount: number, source?: HTMLElement) { const origin = source?.getBoundingClientRect(); state.balance += amount; state.ledger.deposits += amount; persist(); closeModals(); render(); if (origin) animateRecharge(origin); }
function animateRecharge(origin: DOMRect) { const target = app.querySelector<HTMLElement>('[data-balance-target]'); if (!target) return; const targetRect = target.getBoundingClientRect(); const startX = origin.left + origin.width / 2; const startY = origin.top + origin.height / 2; const offsetX = targetRect.left + targetRect.width / 2 - startX; const offsetY = targetRect.top + targetRect.height / 2 - startY; for (let index = 0; index < 9; index += 1) { const coin = document.createElement('span'); coin.className = 'recharge-coin'; coin.textContent = 'R'; coin.style.left = `${startX}px`; coin.style.top = `${startY}px`; coin.style.setProperty('--fly-x', `${offsetX + (Math.random() - 0.5) * 38}px`); coin.style.setProperty('--fly-y', `${offsetY + (Math.random() - 0.5) * 26}px`); coin.style.animationDelay = `${index * 38}ms`; coin.addEventListener('animationend', () => coin.remove(), { once: true }); document.body.append(coin); } target.classList.remove('balance-arrived'); void target.offsetWidth; target.classList.add('balance-arrived'); window.setTimeout(() => target.classList.remove('balance-arrived'), 900); }
function handleAction(action: string) { if (action === 'bet-down') betIndex = Math.max(0, betIndex - 1); if (action === 'bet-up') betIndex = Math.min(GAME_CONFIG.betSteps.length - 1, betIndex + 1); if (action === 'shop') openModal('shop'); if (action === 'ledger') openModal('ledger'); if (action === 'rules') openModal('rules'); if (action === 'volume') { app.querySelector('[data-volume-popover]')?.classList.toggle('hidden'); return; } if (action === 'close-free-summary') { freeSummary = null; freeSessionWin = 0; render(); return; } if (action === 'enter-free-game') { freeGameReady = false; render(); return; } if (action === 'close') closeModals(); if (action === 'mute') { toggleMute(); render(); return; } if (action === 'sound') { toggleMusic(); render(); return; } if (action === 'gm') { const amount = Number(prompt('输入增加的 R 金额', '9999999')); if (amount > 0) deposit(amount); return; } if (action === 'rescue') { state.balance += 10; state.rescueUsed = true; persist(); closeModals(); render(); return; } if (action === 'spin') { runSpin(); return; } render(); }
function chooseDragon(id: string) { state.dragonId = id; state.freeSpins += DRAGONS.find((item) => item.id === id)?.spins ?? 0; pendingFreeGameSelection = false; state.pendingFreeGameSelection = false; freeSummary = null; freeGameReady = false; dragonSelection = false; persist(); render(); window.setTimeout(runSpin, 280); }
function finishSpin() { if (!pendingResult) return; if (spinTimer !== null) window.clearTimeout(spinTimer); stopTimers.forEach((timer) => window.clearTimeout(timer)); stopTimers = []; const wasFreeSpin = state.freeSpins > 0; const wager = wasFreeSpin ? 0 : bet(); state.balance -= wager; if (wasFreeSpin) state.freeSpins -= 1; lastResult = pendingResult; pendingResult = null; grid = lastResult.grid; if (wasFreeSpin) { freeSessionWin += lastResult.totalWin; state.freeGameWin = freeSessionWin; } else state.balance += lastResult.totalWin; state.ledger.wagered += wager; state.ledger.won += lastResult.totalWin; state.ledger.spins += 1; state.scatterMisses = lastResult.scatterCount >= 3 ? 0 : state.scatterMisses + 1; if (lastResult.totalWin) playWinSound(lastResult.totalWin); lastResult.grid[0].forEach((_, column) => { if (!scatterSoundedColumns.has(column) && lastResult?.grid.some((row) => row[column] === 'scatter')) playScatterSound(column); }); state.history.unshift({ time: new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }), bet: wager, win: lastResult.totalWin, label: wasFreeSpin ? `免费游戏 +${money(lastResult.totalWin)}` : lastResult.scatterCount >= 3 ? `${lastResult.scatterCount} 个龙珠` : lastResult.wins.length ? `${lastResult.wins.length} 组连线` : '未中奖' }); state.history.splice(50); persist(); isSpinning = false; if (wasFreeSpin && lastResult.scatterCount >= 3) { pendingFreeGameSelection = true; state.pendingFreeGameSelection = true; } if (!wasFreeSpin && lastResult.scatterCount >= 3) { dragonSelection = true; freeGameReady = true; freeSummary = null; } else if (wasFreeSpin && state.freeSpins === 0) { if (pendingFreeGameSelection) { dragonSelection = true; freeGameReady = true; freeSummary = null; } else { freeSummary = freeSessionWin; state.balance += state.freeGameWin; state.freeGameWin = 0; persist(); } } if (autoSpins > 0) autoSpins -= 1; persist(); render(); startWinDetails(); if (!dragonSelection && freeSummary === null && autoSpins > 0 && (state.balance >= bet() || state.freeSpins > 0)) window.setTimeout(runSpin, 450); if (!dragonSelection && freeSummary === null && state.freeSpins > 0) window.setTimeout(runSpin, 650); }
function runSpin() { if (isSpinning) { finishSpin(); return; } if (!state.freeSpins && state.balance < bet()) { openModal('rescue'); return; } if (winDisplayTimer !== null) window.clearInterval(winDisplayTimer); winDisplayTimer = null; winDisplayIndex = 0; startMusic(); isSpinning = true; lastResult = null; scatterSoundedColumns = new Set(); const multiplier = state.freeSpins && dragon() ? dragon()!.multipliers[Math.floor(Math.random() * 3)] : 1; pendingResult = spin(bet(), multiplier, dragon()?.id ?? null, Math.random() < scatterPityChance(state.scatterMisses)); playSpinSound(); render(); const reels = app.querySelector<HTMLElement>('[data-reels]'); stopTimers = [0, 1, 2, 3, 4].map((column) => window.setTimeout(() => { reels?.classList.add(`reel-stop-${column}`); if (pendingResult?.grid.some((row) => row[column] === 'scatter')) { scatterSoundedColumns.add(column); playScatterSound(column); } }, 520 + column * 230)); spinTimer = window.setTimeout(finishSpin, 1800); }
window.addEventListener('keydown', (event) => { if (event.key === 'F2') { event.preventDefault(); openModal('shop'); } });
if (state.lastCheckIn !== today()) { state.lastCheckIn = today(); state.rescueUsed = false; persist(); }
render();
